# ─────────────────────────────────────────────────────────────────────────────
# Site Settings
# ─────────────────────────────────────────────────────────────────────────────
title: Fullstack AI Blogs
email: rambabar108@gmail.com
description: >-
  A comprehensive blog covering Python, Machine Learning, Deep Learning,
  NLP, Generative AI, AI Agents, and End-to-End Deployment.
url: "https://rambabar.github.io"  # Your GitHub Pages domain
baseurl: "/learnai-dev.github.io"  # Your repository name (project repo)
github_username: rambabar
linkedin_username: rambabar

# ─────────────────────────────────────────────────────────────────────────────
# Appearance & Theme
# ─────────────────────────────────────────────────────────────────────────────
theme: jekyll-theme-cayman
#theme: minima #cayman
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/  # organized by category/date/title

# ─────────────────────────────────────────────────────────────────────────────
# Plugins
# ─────────────────────────────────────────────────────────────────────────────
plugins:
  - jekyll-feed       # RSS feed
  - jekyll-seo-tag    # SEO meta tags
  - jekyll-sitemap    # Sitemap.xml
  - jekyll-paginate   # Pagination support
  - jekyll-archives   # (optional) generate archives by category/tag
paginate: 5            # 5 posts per page
paginate_path: "/page:num/"

# ─────────────────────────────────────────────────────────────────────────────
# Navigation (used by _includes/nav.html)
# ─────────────────────────────────────────────────────────────────────────────
nav_items:
  - title: Home
    url: "/"
  - title: Categories
    url: "/categories/"
  - title: About
    url: "/about/"

# ─────────────────────────────────────────────────────────────────────────────
# Author Metadata
# ─────────────────────────────────────────────────────────────────────────────
author:
  name: Ramchnadra Babar
  email: rambabar108@gmail.com
  bio: "Sharing practical insights from Python to Generative AI with real-world deployment examples."
  location: India
  avatar: /assets/images/avatar.png

# ─────────────────────────────────────────────────────────────────────────────
# Collections / Categories
# ─────────────────────────────────────────────────────────────────────────────
# We'll use a data file (see _data/categories.yml) to list categories.
# This makes it easier to loop over them in our nav or category index.
collections:
  posts:
    output: true

# ─────────────────────────────────────────────────────────────────────────────
# Exclude
# ─────────────────────────────────────────────────────────────────────────────
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
